words = [
    "afile",
    "augroup",
    "autocmd",
    "autocommands",
    "autoread",
    "autotrigger",
    "autowrite",
    "backupdir",
    "bdelete",
    "breakindent",
    "bufdelete",
    "bufhidden",
    "buflisted",
    "bufnr",
    "bufremove",
    "bufs",
    "buftype",
    "buftypes",
    "cabbrev",
    "catppuccin",
    "cclose",
    "chaitanyabsprip",
    "cmdheight",
    "cmdline",
    "codeaction",
    "colorschemes",
    "commentstring",
    "compl",
    "completeopt",
    "conceallevel",
    "curdir",
    "cursorline",
    "cword",
    "davidmh",
    "diffopt",
    "dropbar",
    "drybalka",
    "edeneast",
    "endfunction",
    "endtry",
    "endwhile",
    "equalalways",
    "everforest",
    "exepath",
    "expandcmd",
    "fargs",
    "fastaction",
    "filereadable",
    "filewritable",
    "fnamemodify",
    "foldexpr",
    "foldlevel",
    "foldlevelstart",
    "foldmethod",
    "folke",
    "gdefault",
    "getcmdpos",
    "getcmdtype",
    "getcwd",
    "gitbrowse",
    "grepformat",
    "grepprg",
    "grug",
    "guifont",
    "hipatterns",
    "hyperlegible",
    "ignorecase",
    "indentexpr",
    "infercase",
    "inoremap",
    "ipairs",
    "isdirectory",
    "jumplist",
    "kanso",
    "keymap",
    "keymaps",
    "lastused",
    "lazydev",
    "lazygit",
    "lclose",
    "lgrep",
    "listchars",
    "loadstring",
    "localleader",
    "loclist",
    "lspconfig",
    "lspsaga",
    "makeprg",
    "markview",
    "menuone",
    "moby",
    "mrufiles",
    "multiwindow",
    "muniftanjim",
    "myvimrc",
    "nargs",
    "navbuddy",
    "navic",
    "nbsp",
    "neanias",
    "neovide",
    "nightfox",
    "nmap",
    "nnoremap",
    "nocommit",
    "noequalalways",
    "nofile",
    "nohidden",
    "nohlsearch",
    "noice",
    "noinsert",
    "nonumber",
    "norelativenumber",
    "noremap",
    "noselect",
    "nospell",
    "notvscode",
    "nowrap",
    "nowrite",
    "nvim",
    "nvimdev",
    "nvimtools",
    "ogrep",
    "olgrep",
    "packpath",
    "patreon",
    "pmizio",
    "popupmenu",
    "powerline",
    "previewwindow",
    "pumblend",
    "pumvisible",
    "qall",
    "qflist",
    "rachartier",
    "saghen",
    "scrolloff",
    "sessionoptions",
    "setf",
    "setlocal",
    "setpos",
    "shada",
    "shiftwidth",
    "sidescrolloff",
    "smartcase",
    "smartindent",
    "smiteshp",
    "softtabstop",
    "splitbelow",
    "splitjoin",
    "startinsert",
    "statuscolumn",
    "statusline",
    "stdpath",
    "strpart",
    "tabnew",
    "tabnr",
    "tabpage",
    "tabpages",
    "termguicolors",
    "textobj",
    "textobject",
    "textobjects",
    "tnoremap",
    "toggleterm",
    "trailspace",
    "tsc",
    "undodir",
    "undofile",
    "undotree",
    "updatetime",
    "useslash",
    "usetab",
    "vimgrep",
    "vimls",
    "vimrc",
    "vtsls",
    "webhooked",
    "wesrupert",
    "whichkey",
    "wildignore",
    "wildignorecase",
    "wildmenu",
    "wildmode",
    "wildoptions",
    "winbar",
    "winblend",
    "wincmd",
    "winhighlight",
    "winid",
    "winnr",
    "winsize",
    "writebackup",
    "yioneko",
    "zindex",
]
