#!/bin/bash

installdir=$(cd "$(dirname "$0")"; pwd)
pushd "$installdir" >/dev/null

# Set up links
nvimdir="$HOME/.config/nvim"
mkdir -p $nvimdir

ln -fsv $installdir/vimrc $HOME/.vimrc
ln -fsv $installdir/init.vim $nvimdir
ln -fsv $installdir/.ideavimrc $HOME/.ideavimrc

# Initialize vim plug
git submodule update --init --recursive

popd >/dev/null
echo Done!
