#!/bin/bash

installdir="$(dirname $0)"

# Set up links
nvimdir="$HOME/.config/nvim"
mkdir -p $nvimdir

ln -fv $installdir/vimrc $HOME/.vimrc
ln -fv $installdir/init.vim $nvimdir
ln -fv $installdir/coc-settings.json $nvimdir
ln -fv $installdir/.ideavimrc $HOME/.ideavimrc

# Initialize vim plug
git submodule update --init --recursive

echo Done!
