#!/bin/bash

installdir="$(dirname $0)"

# Set up links
nvimdir="$HOME/.config/nvim"
mkdir -p $nvimdir

ln -fsv $installdir/vimrc $HOME/.vimrc
ln -fsv $installdir/init.vim $nvimdir
ln -fsv $installdir/.ideavimrc $HOME/.ideavimrc

# Initialize vim plug
git submodule update --init --recursive

echo Done!
